export const config = {
  MODEL: "llama-3.3-70b-versatile",
  TEMPERATURE: 0.2,
  MAX_TOKENS: 120,
  MAX_HISTORY: 20,

  SALE_COMMISSION_PERCENT: 2,
  RENT_COMMISSION_PERCENT: 50,

  REPLY_TIMEOUT: 30 * 60 * 1000,
  FOLLOWUP_TIMEOUT: 2 * 60 * 60 * 1000,
  GAP_BETWEEN_LEADS: 10 * 60 * 1000,
  TYPING_CHAR_MIN: 80,
  TYPING_CHAR_MAX: 250,
  MESSAGE_PAUSE_MIN: 2000,
  MESSAGE_PAUSE_MAX: 5000,

  MAX_MSGS_PER_HOUR: 15,
  MAX_MSGS_PER_DAY_PER_CONTACT: 30,
  MAX_MSGS_PER_DAY_TOTAL: 50,
  ACTIVE_HOURS_START: 7,
  ACTIVE_HOURS_END: 14,
  ACTIVE_HOURS_AFTERNOON_START: 15,
  ACTIVE_HOURS_AFTERNOON_END: 23,
  NO_MESSAGE_DAY: 0,

  CSV_OUTPUT_PATH: "/home/metropolis2/real-estate-atoms/data/collected-leads.csv",
  LEADS_INPUT_PATH: "/home/metropolis2/real-estate-atoms/leads/today.csv"
};
